### ISSUE TITLE
好像没有卸载文档

### ISSUE THREAD

**Issue by xjxjin** [ZingerLittleBee/server_bee-backend#94]
我是采用 下面的安装方式，但是我想卸载，好像没有哪里有文档明显写了怎么卸载

wget https://db.serverbee.app/cli/v1.1.5/serverbee-deploy-x86_64-unknown-linux-musl.zip
unzip serverbee-deploy-x86_64-unknown-linux-musl.zip
./serverbee-deploy

**Comment by xjxjin** [comment]
重启后开机自启动好像失效了, 我的设备是
<img width="514" alt="image" src="https://github.com/ZingerLittleBee/server_bee-backend/assets/35513148/a573019a-5e24-4dd8-819f-c79bb41979c6">

root@x96max:/opt/serverbee# ./serverbee-deploy -a true
thread 'main' panicked at deploy/src/storage_config.rs:71:74:
called `Result::unwrap()` on an `Err` value: Error { kind: SCANNER, problem: "could not find expected ':'", problem_mark: Mark { line: 7, column: 1 }, context: "while scanning a simple key", context_mark: Mark { line: 6, column: 1 } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@x96max:/opt/serverbee# cargo build --bin serverbee-deploy --release
-bash: cargo: command not found
root@x96max:/opt/serverbee# ./serverbee-deploy -p 8081
thread 'main' panicked at deploy/src/storage_config.rs:71:74:
called `Result::unwrap()` on an `Err` value: Error { kind: SCANNER, problem: "could not find expected ':'", problem_mark: Mark { line: 7, column: 1 }, context: "while scanning a simple key", context_mark: Mark { line: 6, column: 1 } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@x96max:/opt/serverbee# ./serverbee-deploy -p 99
thread 'main' panicked at deploy/src/storage_config.rs:71:74:
called `Result::unwrap()` on an `Err` value: Error { kind: SCANNER, problem: "could not find expected ':'", problem_mark: Mark { line: 7, column: 1 }, context: "while scanning a simple key", context_mark: Mark { line: 6, column: 1 } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@x96max:/opt/serverbee# ll
total 18196
drwxr-xr-x 4 root root     4096 Apr 21 00:25 ./
drwxr-xr-x 4 root root     4096 Apr 21 00:31 ../
drwxr-xr-x 3 root root     4096 Apr 21 00:25 db/
-rw-r--r-- 1 root root       63 Apr 21 00:25 deploy-config.yml
-rw-r--r-- 1 root root      533 Apr 21 00:25 deploy.log
-rwxr-xr-x 1 root root 13995696 Oct 21 23:35 serverbee-deploy*
-rw-r--r-- 1 root root  4611228 Oct 21 23:41 serverbee-deploy-aarch64-unknown-linux-musl.zip
drwxr-xr-x 3 root root     4096 Apr 21 00:29 v2.3.0/
root@x96max:/opt/serverbee#

**Comment by ZingerLittleBee** [comment]
卸载只需要把文件夹删除就行了
开机自启需要通过 systemd 来设置，安装完成和文档中都有提示
